# Generated by Django 5.1.2 on 2024-10-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, default='', help_text='Escreva um conteúdo para o Post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
